name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Build docker
        run: make docker-build

      - name: Run docker
        run: make docker-run-detach

      - name: Install docker-tests
        run: yarn workspace docker-tests install

      - name: Test docker
        run: make docker-test
