name: TS

on: [push, pull_request]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: TS install
        run: make ts-install

      - name: Playground Test
        run: make playground-test
